packages:
  - apps/*
  - packages/*
  - internal/*
  - scripts/*
catalog:
  "@clack/prompts": ^0.11.0
  "@manypkg/get-packages": ^3.1.0
  "@types/archiver": 6.0.3
  "@types/node": 22.16.0
  "@vitejs/plugin-vue": 6.0.1
  "@vitejs/plugin-vue-jsx": 5.0.1
  archiver: 7.0.1
  cac: ^6.7.14
  chalk: ^5.6.2
  cross-env: 7.0.3
  dotenv: 16.6.1
  element-plus: 2.10.0
  execa: 9.6.0
  find-up: ^8.0.0
  pkg-types: 2.2.0
  rimraf: 6.0.1
  sass: 1.89.2
  tailwindcss: 3.4.17
  turbo: 2.5.4
  typescript: 5.8.3
  unbuild: 3.6.1
  unplugin-element-plus: 0.10.0
  vite: 7.1.2
  vite-plugin-html: ^3.2.2
  vite-plugin-vue-devtools: ^8.0.3
  vitest: 3.2.4
  vue: 3.5.17
  vue-tsc: 2.2.10
