packages:
  - apps/*
  - packages/*
  - internal/*
  - scripts/*
catalog:
  "@clack/prompts": ^0.11.0
  "@manypkg/get-packages": ^3.1.0
  "@types/node": 22.16.0
  "@vitejs/plugin-vue": 6.0.1
  cac: ^6.7.14
  execa: 9.6.0
  find-up: ^8.0.0
  pkg-types: 2.2.0
  rimraf: 6.0.1
  turbo: 2.5.4
  unbuild: 3.6.1
  vite: 7.1.2
  vue: 3.5.17
